### ISSUE TITLE
Setting up default react-query options for loadUser() query

### ISSUE THREAD

**Issue by morismoze** [alan2207/react-query-auth#11]
Hi @alan2207,

It would be great if react-query-auth provided some props for setting react-query options for this particular query `loadUser()`. The problem is, on every tab/window refocus abovementioned function is called and logically speaking that is not necessary. Shouldn' t be `loadUser()` called by the developer when user data is needed?

**Comment by alan2207** [comment]
Check the latest version, which allows more control over the user query.
