### ISSUE TITLE
question: can I use it with react-query@4 ?

### ISSUE THREAD

**Issue by Developer27149** [alan2207/react-query-auth#12]

**Comment by hamzakat** [comment]
+1

That would be great!

**Comment by alan2207** [comment]
Hi there!

I haven't tried it yet with v4 but I think [this](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#query-keys-and-mutation-keys-need-to-be-an-array) would be a breaking change. Other than that, I am not sure if anything else would be required to change. However, I do plan to update it to accept more options for the user query, so there might be some minor changes in the upcoming version.

**Comment by samdan-d** [comment]
Hi @alan2207,

When would a new version come out? Is there anything to help the progress?

**Comment by diegods-ferreira** [comment]
I'm trying to use it with `@tanstack/react-query@^4.16.1` and it does not work. I don't know what it could be...

![Screenshot_1](https://user-images.githubusercontent.com/62507430/201705412-89abb942-d368-4153-982e-499381babd30.png)

**Comment by hamzakat** [comment]
> I'm trying to use it with `@tanstack/react-query@^4.16.1` and it does not work. I don't know what it could be...
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/62507430/201705412-89abb942-d368-4153-982e-499381babd30.png)

This package hasn't been updated to RQ v.4 yet, but you can check and try the updates proposed in this PR #16

**Comment by diegods-ferreira** [comment]
@hamzakat Thanks, man. I'll check it.

**Comment by alan2207** [comment]
Hey folks, you might want to install the latest version, which supports react-query v4.
