### ISSUE TITLE
Uncaught Error: useAuth must be used within an AuthProvider

### ISSUE THREAD

**Issue by morismoze** [alan2207/react-query-auth#14]
Hi @alan2207,

Sometimes (I can't tell specifically when) I get this error even though `useAuth` is used inside `AuthProvider`. Because this is uncaught error, React unmounts the whole tree (and I'm not using  `useErrorBoundary` on react-query client). What is/might be the reason for this behaviour?

Thanks

**Comment by alan2207** [comment]
Please use the latest version, which supports react-query v4.
