### ISSUE TITLE
How to manage login errors

### ISSUE THREAD

**Issue by raphaelmsr** [alan2207/react-query-auth#17]
Hi ! Thanks for your package

I am wondering, how to pass the server response message all the way to the View using useAuth ?
I played with the axios interceptors but the login function would always succeed but even if I promise.reject in the loginFn, how to get the message to the useAuth props ?

Hope I was clear, it is a very generic issue to be honest.
Logging in wrong credentials, 401 error from the backend with a message -> how do I display the message? 
Thanks !

**Comment by alan2207** [comment]
Please check the latest version, which has breaking API changes.
