### ISSUE TITLE
How can we usine in JS project can someone provide any basic structure to implement 

### ISSUE THREAD

**Issue by marxyes** [alan2207/react-query-auth#2]

**Comment by alan2207** [comment]
This can only be used with React.

Here are the links to the example implementation:

https://github.com/alan2207/react-query-auth/tree/master/sample-app

https://codesandbox.io/s/react-query-auth-demo-fvvvt

**Comment by marxyes** [comment]
Sorry I was asking for React project based on JS, not in typescript , but some how I setup it on React(js) project

**Comment by alan2207** [comment]
I see. Of course it can, everything will work the same.

**Comment by marxyes** [comment]
![image](https://user-images.githubusercontent.com/58813796/130334597-fdf33321-9d72-4078-9075-226d6e8dcf42.png)

**Comment by alan2207** [comment]
Can you try this?:

https://stackoverflow.com/a/34563571

**Comment by marxyes** [comment]
> Can you try this?:
> 
> https://stackoverflow.com/a/34563571

Yes Worked  as mentioned in Solution 
also there is another solution on same thread that is

import react from react  in  react-query.js

**import React from 'react';**

import { QueryClient, QueryClientProvider } from "react-query";
// import { ReactQueryDevtools } from 'react-query/devtools';

export const queryClient = new QueryClient();

export function ReactQueryProvider({ children }) {
  return (
    <QueryClientProvider client={queryClient}>
      {/* <ReactQueryDevtools /> */}
      {children}
    </QueryClientProvider>
  );
}


Thanks, @alan2207
