### ISSUE TITLE
[Next.js] Issue while using the hooks

### ISSUE THREAD

**Issue by StevenOng97** [alan2207/react-query-auth#20]
Hello @alan2207, i'm getting into this bug when I tried to call useLogin hook from our library. As I research, I need to put queryClient in the root file which I've already done.

<img width="1792" alt="Screen Shot 2023-02-16 at 5 15 56 PM" src="https://user-images.githubusercontent.com/61964358/219337064-da22e906-81be-484b-8ee6-af1c373418a1.png">

<img width="1792" alt="Screen Shot 2023-02-16 at 5 17 18 PM" src="https://user-images.githubusercontent.com/61964358/219337070-f109b9dd-ca8f-4987-aac9-f8220d0f1bd0.png">

<img width="1792" alt="Screen Shot 2023-02-16 at 5 15 31 PM" src="https://user-images.githubusercontent.com/61964358/219337030-ecf9b0cc-7608-4da3-ab27-bd819c4db84c.png">

**Comment by AquamanRanda** [comment]
getting the same issue here @alan2207. Please help to resolve this!

**Comment by aktarulrahul-tec** [comment]
i'm also getting the same issue. please help me out.

**Comment by alan2207** [comment]
Hey, thanks for reporting this, it was caused by dts-cli. Now the library has been migrated to tsup. Let me know if the issue has been resolved.

**Comment by StevenOng97** [comment]
Hi @alan2207 , there's another issue after your upgrade

Module not found: Default condition should be last one

<img width="1792" alt="Screen Shot 2023-02-17 at 9 53 10 AM" src="https://user-images.githubusercontent.com/61964358/219537767-42565d3e-54cc-40ed-8579-f2e82513463e.png">

**Comment by alan2207** [comment]
@StevenOng97 , try again by installing the latest version `2.1.1`.

**Comment by StevenOng97** [comment]
It's working. Thanks for you support
