### ISSUE TITLE
[Nextjs] Issue with 2.1.1 

### ISSUE THREAD

**Issue by AquamanRanda** [alan2207/react-query-auth#22]
hey @alan2207, I recently installed the updated version of react-query-auth 2.1.1 and I am getting an error 

cannot find module: 'react/jsx-runtime' 
did you mean react/jsx-runtime.js

![image](https://user-images.githubusercontent.com/41387473/219642685-150195e3-a34c-46bc-bca8-7fbc54d6a794.png)

**Comment by alan2207** [comment]
hey @AquamanRanda, can you provide a reproducible repo?

**Comment by AquamanRanda** [comment]
https://github.com/aktarulrahul-tec/react-query-auth-error -> this is the reproducible repo

**Comment by alan2207** [comment]
@AquamanRanda , thanks for providing the repo. You can try it now with version `2.1.2`

**Comment by AquamanRanda** [comment]
same issue @alan2207 

https://github.com/aktarulrahul-tec/react-query-auth-error

![image](https://user-images.githubusercontent.com/41387473/221339609-c4eaec7c-1bb0-485c-b0f5-c1b480032df4.png)

![image](https://user-images.githubusercontent.com/41387473/221339613-865aa6dd-f150-4b81-a28f-b21e3f41fd5d.png)

deleted node_modules & also ran the command npm cache clean as well

**Comment by alan2207** [comment]
@AquamanRanda   Update your React versions to 18

**Comment by AquamanRanda** [comment]
@alan2207 Yes it works. Thank you
