### ISSUE TITLE
set query-retries

### ISSUE THREAD

**Issue by zouterover** [alan2207/react-query-auth#7]
My general `queryClientConfig` for react-query is more or less the default one:
```
queryClientConfig: {
        defaultOptions: {
            queries: {
                retry: 2,
                refetchOnMount: "always",
                refetchOnWindowFocus: "always",
                refetchOnReconnect: "always",
                cacheTime: 1000*30,
                refetchInterval: false,
                refetchIntervalInBackground: false,
                suspense: false,
                staleTime: 1000 * 30,
            },
            mutations: {
                retry: 2,
            },
        }
    },

```

When I login with wrong login-details I get a 401, however I get three 401's (mutations are retried twice). When I reconfigure and set retry to 0 it indeed works as I want. 

You can also set retry config per request:
https://react-query.tanstack.com/guides/query-retries

So I would like to set number of retries only for login, but how would I do that using `react-query-auth`?

**Comment by alan2207** [comment]
Hey, you might want to install the latest version, which allows more granular control over the queries and mutations.
